MissingPersonWebApp/MissingPersonWebApp/Controllers/FacebookController.cs
using FacebookLibrary.Controllers;
using Microsoft.AspNetCore.Mvc;
using MissingPersonWebApp.Logic;
using MissingPersonWebApp.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;

namespace MissingPersonWebApp.Controllers
{
    public class FacebookController : Controller
    {
        public void PostImage(MissingPersonModel model)
        {
            ManageMissingPersonLogic logic = new ManageMissingPersonLogic();
            FacebookLogic facebookLogic = new FacebookLogic();
            FacebookModel facebookModel = new FacebookModel();
            FacebookUtilityController utility = new FacebookUtilityController();

            model.FacebookText = facebookLogic.CreateFacebookMessage(model);
            string path = model.ImagePath + model.ImageName;

            facebookModel = facebookLogic.GetFacebookAccountDetail();
            model.FacebookPostId  = utility.PostImage(facebookModel.PageAccessToken, facebookModel.AppId, facebookModel.AppSecret, path, model.FacebookText);

            model.FacebookAccountId = facebookModel.FacebookAccountId;
            logic.UpdateFacebookPostId(model);
        }

        public ActionResult FacebookDashboard()
        {
            bool isSessionExist = HttpContext.Session.IsAvailable;
            if (isSessionExist)
            {
                HttpContext.Session.TryGetValue("role", out byte[] value);
                string role = string.Empty;
                if (value != null)
                {
                    role = Encoding.ASCII.GetString(value).Replace(@"\", "");
                    role = JsonConvert.DeserializeObject<string>(role);

                }
                if (role == "admin")
                {
                    ViewData["role"] = "admin";
                }
                else
                {
                    ViewData["role"] = "user";
                }
            }

            return View();
        }

        public ActionResult GetFacebookAccounts()
        {
            List<FacebookModel> List = new List<FacebookModel>();
            FacebookLogic Logic = new FacebookLogic();
            List = Logic.GetAllFacebookAccountDetail();

            return Json(new
            {
                draw = 1,
                recordsTotal = List.Count(),
                recordsFiltered = List.Count(),
                data = List
            });
        }

        public ActionResult AddFacebookAccount()
        {
            bool isSessionExist = HttpContext.Session.IsAvailable;
            if (isSessionExist)
            {
                HttpContext.Session.TryGetValue("role", out byte[] value);
                string role = string.Empty;
                if (value != null)
                {
                    role = Encoding.ASCII.GetString(value).Replace(@"\", "");
                    role = JsonConvert.DeserializeObject<string>(role);

                }
                if (role == "admin")
                {
                    ViewData["role"] = "admin";
                }
                else
                {
                    ViewData["role"] = "user";
                }
            }

            return View();
        }

        [HttpPost]
        public ActionResult AddFacebookAccount(FacebookModel model)
        {
            if (ModelState.IsValid)
            {
                FacebookLogic logic = new FacebookLogic();
                logic.AddFacebookAccount(model);
                return Redirect("FacebookDashboard");
            }

            bool isSessionExist = HttpContext.Session.IsAvailable;
            if (isSessionExist)
            {
                HttpContext.Session.TryGetValue("role", out byte[] value);
                string role = string.Empty;
                if (value != null)
                {
                    role = Encoding.ASCII.GetString(value).Replace(@"\", "");
                    role = JsonConvert.DeserializeObject<string>(role);

                }
                if (role == "admin")
                {
                    ViewData["role"] = "admin";
                }
                else
                {
                    ViewData["role"] = "user";
                }
            }

            return View(model);
        }


        public ActionResult UpdateFacebookAccount(int id)
        {
            bool isSessionExist = HttpContext.Session.IsAvailable;
            if (isSessionExist)
            {
                HttpContext.Session.TryGetValue("role", out byte[] value);
                string role = string.Empty;
                if (value != null)
                {
                    role = Encoding.ASCII.GetString(value).Replace(@"\", "");
                    role = JsonConvert.DeserializeObject<string>(role);

                }
                if (role == "admin")
                {
                    ViewData["role"] = "admin";
                }
                else
                {
                    ViewData["role"] = "user";
                }
            }
            ViewData["Id"] = id;
            return View();
        }

        [HttpPost]
        public ActionResult UpdateFacebookAccount(FacebookModel model)
        {
            if (ModelState.IsValid)
            {
                FacebookLogic logic = new FacebookLogic();
                logic.UpdateFacebookAccount(model);
                return Redirect("FacebookDashboard");
            }

            return View(model);
        }

        public JsonResult GetFacebookAccountById(int id)
        {
            FacebookLogic logic = new FacebookLogic();
            FacebookModel model = new FacebookModel();

            model = logic.GetFacebookAccountById(id);

            if (model.FacebookAccountId > 0)
                return Json(new { data = model });
            else
                return null;

        }
    }
}

MissingPersonWebApp/MissingPersonWebApp/Views/Facebook/AddFacebookAccount.cshtml
@model MissingPersonWebApp.Models.FacebookModel

@{
    ViewBag.Title = "Add Facebook Account";
}

<link href="~/css/CSS/animate.min.css" rel="stylesheet" />
<link href="~/css/CSS/bootstrap.min.css" rel="stylesheet" />
<link href="~/css/CSS/font-awesome.min.css" rel="stylesheet" />
<link href="~/css/CSS/main.css" rel="stylesheet" />
<link href="~/css/CSS/owl.carousel.css" rel="stylesheet" />
<link href="~/css/CSS/responsive.css" rel="stylesheet" />
<link href="https://cdn.datatables.net/1.11.5/css/jquery.dataTables.min.css" rel="stylesheet" />

<style>

    .switch {
        position: relative;
        display: inline-block;
        width: 60px;
        height: 34px;
    }

        .switch input {
            opacity: 0;
            width: 0;
            height: 0;
        }

    .slider {
        position: absolute;
        cursor: pointer;
        top: 0;
        left: 0;
        right: 0;
        bottom: 0;
        background-color: #ccc;
        -webkit-transition: .4s;
        transition: .4s;
    }

        .slider:before {
            position: absolute;
            content: "";
            height: 26px;
            width: 26px;
            left: 4px;
            bottom: 4px;
            background-color: white;
            -webkit-transition: .4s;
            transition: .4s;
        }

    input:checked + .slider {
        background-color: #b3340e;
    }

    input:focus + .slider {
        box-shadow: 0 0 1px #2196F3;
    }

    input:checked + .slider:before {
        -webkit-transform: translateX(26px);
        -ms-transform: translateX(26px);
        transform: translateX(26px);
    }

    /* Rounded sliders */
    .slider.round {
        border-radius: 34px;
    }

        .slider.round:before {
            border-radius: 50%;
        }


    .center {
        display: block;
        margin-left: auto;
        margin-right: auto;
        width: 20%;
    }


    .dropdown {
        overflow: hidden;
        color: blue;
    }

        .dropdown .dropbtn {
            font-size: 16px;
            border: none;
            outline: none;
            color: blue;
            padding: 14px 16px;
            background-color: inherit;
            font-family: inherit;
            margin: 0;
        }



    .dropdown-content {
        display: none;
        background-color: #f9f9f9;
        min-width: 50px;
        margin-left: -100px;
    }

        .dropdown-content a {
            color: black;
            padding: 12px 16px;
            text-decoration: none;
            display: block;
            text-align: right;
        }

            .dropdown-content a:hover {
                background-color: #ddd;
            }

    .dropdown:hover .dropdown-content {
        display: block;
    }
</style>

<section id="hero-area">
    <img class="img-responsive" src="~/Image/header1.png" alt="">
</section>

<div class="container body-content">
    <nav id="navigation">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="block">
                        <nav class="navbar navbar-default">
                            <div class="container-fluid">
                                <!-- Brand and toggle get grouped for better mobile display -->
                                <div class="navbar-header">
                                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                                        <span class="sr-only">Toggle navigation</span>
                                        <span class="icon-bar"></span>
                                        <span class="icon-bar"></span>
                                        <span class="icon-bar"></span>
                                    </button>
                                    @*<a class="navbar-brand" href="#">
                                            <img src="~/Image/logo.png" alt="Logo">
                                        </a>*@

                                </div>

                                <!-- Collect the nav links, forms, and other content for toggling -->
                                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                                    <div class="pull-right">
                                        <span><button class="btn btn-outline-light"><a href="/Dashboard/Dashboard">Home</a></button></span>&nbsp&nbsp&nbsp
                                        <span><button class="btn btn-outline-light"><a href="">About us</a></button></span>&nbsp&nbsp&nbsp
                                        <span><button class="btn btn-outline-light"><a href="">Contact us</a></button></span>&nbsp&nbsp&nbsp
                                        @{
                                            var role = ViewData["role"];
                                            if (role != null && role.ToString() == "admin")
                                            {
                                                <span><button class="btn btn-outline-light"><a href="">Blog</a></button></span>
                                                <span><button class="btn btn-outline-light"><a href="/MissingPerson/ManageMissingPerson"> Manage Missing Person</a></button></span>
                                                <span class="dropdown">
                                                    <button class="btn btn-outline-light" style="color: #6590cc;">Manage Account&nbsp<i class="fa fa-caret-down"></i></button>
                                                    <span class="dropdown-content">
                                                        <a href="/Facebook/FacebookDashboard"> Manage Facebook Accounts</a>
                                                        <a href="/Twitter/TwitterDashboard"> Manage Twitter Accounts</a>
                                                        <a href="" onclick="Logout()"> Logout </a>
                                                    </span>
                                                </span>
                                            }

                                        }
                                    </div>
                                </div><!-- /.navbar-collapse -->
                            </div><!-- /.container-fluid -->
                        </nav>
                    </div>
                </div><!-- .col-md-12 close -->
            </div><!-- .row close -->
        </div><!-- .container close -->
    </nav><!-- header close -->
    <!--Header end-->
    <div>
        <button type="button" class="btn btn-info m-2" style="float: right;" id="facebookaccountlist">Back to List</button>
        @*@Html.ActionLink("Back to List", "ManageMissingPerson")*@
    </div>
    <div class="col-md-10" style="padding-left: 330px">
        <div class="bg-light rounded h-100 p-4">
            @using (Html.BeginForm("AddFacebookAccount", "Facebook", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        <h4>Add Facebook Account</h4>
                        <hr />
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                        <div class="form-group">
                            @*<label class="control-label col-md-2">First Name</label>*@
                            <div class="col-md-4" style="padding-left: 71px;">@Html.LabelFor(model => model.AppId, "App Id")</div>
                            <div class="col-md-8">
                                @Html.EditorFor(model => model.AppId, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.AppId, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-4" style="padding-left: 71px;">
                                @Html.LabelFor(model => model.AppName, "App Name")
                            </div>
                            <div class="col-md-8">
                                @Html.EditorFor(model => model.AppName, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.AppName, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-4" style="padding-left: 71px;">
                                @Html.LabelFor(model => model.AppSecret, "App Secret")
                            </div>
                            <div class="col-md-8">
                                @Html.EditorFor(model => model.AppSecret, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.AppSecret, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-4" style="padding-left: 71px;">
                                @Html.LabelFor(model => model.PageAccessToken, "Page Access Token")
                            </div>
                            <div class="col-md-8">
                                @Html.EditorFor(model => model.PageAccessToken, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.PageAccessToken, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-5" style="padding-left: 71px;">
                                <label>Enable</label>
                            </div>
                            <div class="col-md-7">
                                <label class="switch">
                                    <input type="checkbox" id="Enable" data-val="true" value="true" name="Enable">
                                    <span class="slider round"></span>
                                </label>
                            </div>
                            <input name="Enable" type="hidden" value="false" />
                        </div>
                       
                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10" style="padding-left: 169px;">
                                <input type="submit" value="Create" class="btn btn-info" style="" />
                            </div>
                        </div>
                    </div>
                }
            }
        </div>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>
<script src="~/js/bootstrap.js"></script>

<script>

    $(document).ready(function () {
     //facebookaccountlist

        $("#facebookaccountlist").click(function () {
            window.location.href = window.location.origin + "/Facebook/FacebookDashboard";
        });
    });



</script>

MissingPersonWebApp/MissingPersonWebApp/Views/Facebook/UpdateFacebookAccount.cshtml
@model MissingPersonWebApp.Models.FacebookModel

@{
    ViewBag.Title = "Add Facebook Account";
}

<link href="~/css/CSS/animate.min.css" rel="stylesheet" />
<link href="~/css/CSS/bootstrap.min.css" rel="stylesheet" />
<link href="~/css/CSS/font-awesome.min.css" rel="stylesheet" />
<link href="~/css/CSS/main.css" rel="stylesheet" />
<link href="~/css/CSS/owl.carousel.css" rel="stylesheet" />
<link href="~/css/CSS/responsive.css" rel="stylesheet" />
<link href="https://cdn.datatables.net/1.11.5/css/jquery.dataTables.min.css" rel="stylesheet" />

<style>

    .switch {
        position: relative;
        display: inline-block;
        width: 60px;
        height: 34px;
    }

        .switch input {
            opacity: 0;
            width: 0;
            height: 0;
        }

    .slider {
        position: absolute;
        cursor: pointer;
        top: 0;
        left: 0;
        right: 0;
        bottom: 0;
        background-color: #ccc;
        -webkit-transition: .4s;
        transition: .4s;
    }

        .slider:before {
            position: absolute;
            content: "";
            height: 26px;
            width: 26px;
            left: 4px;
            bottom: 4px;
            background-color: white;
            -webkit-transition: .4s;
            transition: .4s;
        }

    input:checked + .slider {
        background-color: #b3340e;
    }

    input:focus + .slider {
        box-shadow: 0 0 1px #2196F3;
    }

    input:checked + .slider:before {
        -webkit-transform: translateX(26px);
        -ms-transform: translateX(26px);
        transform: translateX(26px);
    }

    /* Rounded sliders */
    .slider.round {
        border-radius: 34px;
    }

        .slider.round:before {
            border-radius: 50%;
        }


    .center {
        display: block;
        margin-left: auto;
        margin-right: auto;
        width: 20%;
    }

    .dropdown {
        overflow: hidden;
        color: blue;
    }

        .dropdown .dropbtn {
            font-size: 16px;
            border: none;
            outline: none;
            color: blue;
            padding: 14px 16px;
            background-color: inherit;
            font-family: inherit;
            margin: 0;
        }



    .dropdown-content {
        display: none;
        background-color: #f9f9f9;
        min-width: 50px;
        margin-left: -100px;
    }

        .dropdown-content a {
            color: black;
            padding: 12px 16px;
            text-decoration: none;
            display: block;
            text-align: right;
        }

            .dropdown-content a:hover {
                background-color: #ddd;
            }

    .dropdown:hover .dropdown-content {
        display: block;
    }
</style>

<section id="hero-area">
    <img class="img-responsive" src="~/Image/header1.png" alt="">
</section>

<div class="container body-content">
    <nav id="navigation">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="block">
                        <nav class="navbar navbar-default">
                            <div class="container-fluid">
                                <!-- Brand and toggle get grouped for better mobile display -->
                                <div class="navbar-header">
                                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                                        <span class="sr-only">Toggle navigation</span>
                                        <span class="icon-bar"></span>
                                        <span class="icon-bar"></span>
                                        <span class="icon-bar"></span>
                                    </button>
                                    @*<a class="navbar-brand" href="#">
                                            <img src="~/Image/logo.png" alt="Logo">
                                        </a>*@

                                </div>

                                <!-- Collect the nav links, forms, and other content for toggling -->
                                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                                    <div class="pull-right">
                                        <span><button class="btn btn-outline-light"><a href="/Dashboard/Dashboard">Home</a></button></span>&nbsp&nbsp&nbsp
                                        <span><button class="btn btn-outline-light"><a href="">About us</a></button></span>&nbsp&nbsp&nbsp
                                        <span><button class="btn btn-outline-light"><a href="">Blog</a></button></span>&nbsp&nbsp&nbsp
                                        <span><button class="btn btn-outline-light"><a href="">Contacts</a></button></span>&nbsp&nbsp&nbsp
                                        @{
                                            var role = ViewData["role"];
                                            if (role != null && role.ToString() == "admin")
                                            {
                                                <span><button class="btn btn-outline-light"><a href="/MissingPerson/ManageMissingPerson">Manage Missing Person</a></button></span>
                                                <span class="dropdown">
                                                    <button class="btn btn-outline-light" style="color: #6590cc;">Manage Account&nbsp<i class="fa fa-caret-down"></i></button>
                                                    <span class="dropdown-content">
                                                        <a href="/Facebook/FacebookDashboard">Manage Facebook Accounts</a>
                                                        <a href="/Twitter/TwitterDashboard">Manage Twitter Accounts</a>
                                                        <a href="" onclick="Logout()">Logout</a>
                                                    </span>
                                                </span>
                                                @*<span><button class="btn btn-outline-light"><a href=""><img class="img-responsive" src="~/Image/Admin_image.png" style="width: 21px;" alt=""><span class="pull-right">Logout</span></a></button></span>*@

                                            }

                                        }
                                    </div>
                                </div><!-- /.navbar-collapse -->
                            </div><!-- /.container-fluid -->
                        </nav>
                    </div>
                </div><!-- .col-md-12 close -->
            </div><!-- .row close -->
        </div><!-- .container close -->
    </nav><!-- header close -->
    <!--Header end-->
    <div>
        <button type="button" class="btn btn-info m-2" style="float: right;" id="facebookaccountlist">Back to List</button>
        @*@Html.ActionLink("Back to List", "ManageMissingPerson")*@
    </div>
    <div class="col-md-10" style="padding-left: 330px">
        <div class="bg-light rounded h-100 p-4">
            @using (Html.BeginForm("UpdateFacebookAccount", "Facebook", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        <h4>Update Facebook Account</h4>
                        <hr />
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                        <div class="form-group">
                            @*<label class="control-label col-md-2">First Name</label>*@
                            <div class="col-md-4" style="padding-left: 71px;">@Html.LabelFor(model => model.AppId, "App Id")</div>
                            <div class="col-md-8">
                                @Html.EditorFor(model => model.AppId, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.AppId, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-4" style="padding-left: 71px;">
                                @Html.LabelFor(model => model.AppName, "App Name")
                            </div>
                            <div class="col-md-8">
                                @Html.EditorFor(model => model.AppName, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.AppName, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-4" style="padding-left: 71px;">
                                @Html.LabelFor(model => model.AppSecret, "App Secret")
                            </div>
                            <div class="col-md-8">
                                @Html.EditorFor(model => model.AppSecret, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.AppSecret, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-4" style="padding-left: 71px;">
                                @Html.LabelFor(model => model.PageAccessToken, "Page Access Token")
                            </div>
                            <div class="col-md-8">
                                @Html.EditorFor(model => model.PageAccessToken, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.PageAccessToken, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-5" style="padding-left: 71px;">
                                <label>Enable</label>
                            </div>
                            <div class="col-md-7">
                                <label class="switch">
                                    <input type="checkbox" id="Enable" data-val="true" value="true" name="Enable">
                                    <span class="slider round"></span>
                                </label>
                            </div>
                            <input name="Enable" type="hidden" value="false" />
                        </div>
                        <input type="hidden" name="FacebookAccountId" id="facebookAccId" />
                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10" style="padding-left: 169px;">
                                <input type="submit" value="Update" class="btn btn-info" style="" />
                            </div>
                        </div>
                    </div>
                }
            }
        </div>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>
<script src="~/js/bootstrap.js"></script>

<script>

    $(document).ready(function () {

        let id = @Html.Raw(Json.Serialize(ViewData["Id"]));

        if (id > 0) {
            $.ajax({
                url: window.location.origin + "/Facebook/GetFacebookAccountById?id=" + id,
                success: function (result) {
                    debugger;

                    $("#facebookAccId").val(result.data.facebookAccountId);
                    $("#AppId").val(result.data.appId);
                    $("#AppName").val(result.data.appName);
                    $("#AppSecret").val(result.data.appSecret);
                    $("#PageAccessToken").val(result.data.pageAccessToken);

                    if (result.data.enable) {
                        $('#Enable').prop('checked', true);
                    }
              
                }
            });
        }

        $("#facebookaccountlist").click(function () {
            window.location.href = window.location.origin + "/Facebook/FacebookDashboard";
        });
    });



</script>