MissingPersonWebApp/MissingPersonWebApp/Controllers/MissingPersonController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using MissingPersonWebApp.Logic;
using MissingPersonWebApp.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using MissingPersonWebApp.Controllers;
using FacebookUtility;
using System.Text;
using Newtonsoft.Json;

namespace MissingPersonWebApp.Controllers
{
   
    public class MissingPersonController : Controller
    {
        [Obsolete]
        private readonly IHostingEnvironment _hostingEnvironment;

        [Obsolete]
        public MissingPersonController(IHostingEnvironment hostingEnvironment)
        {
            _hostingEnvironment = hostingEnvironment;
        }


        // GET: MissingPerson Details
        public ActionResult ManageMissingPerson()
        {
            bool isSessionExist = HttpContext.Session.IsAvailable;
            if (isSessionExist)
            {
                HttpContext.Session.TryGetValue("role", out byte[] value);
                string role = string.Empty;
                if (value != null)
                {
                    role = Encoding.ASCII.GetString(value).Replace(@"\", "");
                    role = JsonConvert.DeserializeObject<string>(role);

                }
                if (role == "admin")
                {
                    ViewData["role"] = "admin";
                }
                else
                {
                    ViewData["role"] = "user";
                }
            }
            return View();
        }


        public ActionResult GetMissingPeopleDetail()
        {
            List<MissingPersonModel> missingPeopleList = new List<MissingPersonModel>();
            ManageMissingPersonLogic missingPersonLogic = new ManageMissingPersonLogic();
            missingPeopleList = missingPersonLogic.GetMissingPeopleDetail();

            return Json(new
            {
                draw = 1,
                recordsTotal = missingPeopleList.Count(),
                recordsFiltered = missingPeopleList.Count(),
                data = missingPeopleList
            });
        }

        public ActionResult AddMissingPerson()
        {
            return View();
        }

        [HttpPost]
        [Obsolete]
        public ActionResult AddMissingPerson(MissingPersonModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    ManageMissingPersonLogic logic = new ManageMissingPersonLogic();
                    model.ImageName = UploadedFile(model);
                    model.ImagePath = _hostingEnvironment.WebRootPath + @"\\Image\\MissingPeopleImages\\";

                    model.Id = logic.SaveMissingPersonDetail(model);

                    if(model.Id > 0 && model.PublishonTwitter)
                    {
                        TwitterController twitter = new TwitterController();
                        var result = Task.Run(async () =>
                        {
                            await twitter.PostImage(model);
                        });
                    }

                    if (model.Id > 0 && model.PublishonFacebook)
                    {
                        FacebookController facebook = new FacebookController();
                        facebook.PostImage(model);
                    }

                    return Redirect("ManageMissingPerson");
                }
                return View(model);
            }
            catch (Exception ex)
            {
                ViewBag.Message = "";
                return View();
            }
        }

        public ActionResult UpdateMissingPerson(int id)
        {
            ViewData["Id"] = id;

            return View();
        }

        [HttpPost]
        public ActionResult UpdateMissingPerson(MissingPersonModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    ManageMissingPersonLogic logic = new ManageMissingPersonLogic();
                    bool isUpdated = logic.UpdateMissingPersonDetail(model);

                    MissingPersonModel personData = new MissingPersonModel();
                    personData = logic.GetMissingPersonDetailById(model.Id);

                    if (personData.TwitterPostId == null && model.PublishonTwitter)
                    {
                        TwitterController twitter = new TwitterController();
                        var result = Task.Run(async () =>
                        {
                            await twitter.PostImage(model);
                        });
                    }


                    if (personData.FacebookPostId == null && model.PublishonFacebook)
                    {
                        FacebookController facebook = new FacebookController();
                        facebook.PostImage(model);
                    }


                    return Redirect("ManageMissingPerson");
                }
                ViewData["Id"] = model.Id;
                return View(model);
            }
            catch(Exception ex)
            {
                return View();
            }
            
        }

        public ActionResult DeleteMissingPerson(int id)
        {
            ManageMissingPersonLogic logic = new ManageMissingPersonLogic();
            bool isDeleted = logic.DeleteMissingPerson(id);
            return Json(new { data = isDeleted });
        }


        public JsonResult GetMissingPersonDetailById(int id)
        {
            ManageMissingPersonLogic logic = new ManageMissingPersonLogic();
            MissingPersonModel model = new MissingPersonModel();

            model = logic.GetMissingPersonDetailById(id);

            if (model.Id > 0)
                return Json(new { data = model });
            else
                return null;

        }


        private string UploadedFile(MissingPersonModel model)
        {
            string uniqueFileName = null;

            if (model.File != null)
            {
                string uploadsFolder = Path.Combine(_hostingEnvironment.WebRootPath, "Image/MissingPeopleImages");
                uniqueFileName = Guid.NewGuid().ToString() + "_" + model.File.FileName.Replace(" ", "");
                string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    model.File.CopyTo(fileStream);
                }
            }
            return uniqueFileName;
        }

    }
}

MissingPersonWebApp/MissingPersonWebApp/Views/MissingPerson/AddMissingPerson.cshtml
@model MissingPersonWebApp.Models.MissingPersonModel

@{
    ViewBag.Title = "AddMissingPerson";
}

<link href="~/css/CSS/animate.min.css" rel="stylesheet" />
<link href="~/css/CSS/bootstrap.min.css" rel="stylesheet" />
<link href="~/css/CSS/font-awesome.min.css" rel="stylesheet" />
<link href="~/css/CSS/main.css" rel="stylesheet" />
<link href="~/css/CSS/owl.carousel.css" rel="stylesheet" />
<link href="~/css/CSS/responsive.css" rel="stylesheet" />
<link href="https://cdn.datatables.net/1.11.5/css/jquery.dataTables.min.css" rel="stylesheet" />

<style>

    .switch{
        position: relative;
        display: inline-block;
        width: 60px;
        height: 34px;
    }

        .switch input {
        opacity: 0;
        width: 0;
        height: 0;
    }

    .slider {
        position: absolute;
        cursor: pointer;
        top: 0;
        left: 0;
        right: 0;
        bottom: 0;
        background-color: #ccc;
        -webkit-transition: .4s;
        transition: .4s;
    }

        .slider:before {
            position: absolute;
            content: "";
            height: 26px;
            width: 26px;
            left: 4px;
            bottom: 4px;
            background-color: white;
            -webkit-transition: .4s;
            transition: .4s;
        }

    input:checked + .slider {
        background-color: #b3340e;
    }

    input:focus + .slider {
        box-shadow: 0 0 1px #2196F3;
    }

    input:checked + .slider:before {
        -webkit-transform: translateX(26px);
        -ms-transform: translateX(26px);
        transform: translateX(26px);
    }

    /* Rounded sliders */
    .slider.round {
            border-radius: 34px;
        }

    .slider.round:before {
            border-radius: 50%;
        }


    .center {
        display: block;
        margin-left: auto;
        margin-right: auto;
        width: 20%;
    }

</style>

<section id="hero-area">
    <img class="img-responsive" src="~/Image/header1.png" alt="">
</section>

<div class="container body-content">
    <nav id="navigation">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="block">
                        <nav class="navbar navbar-default">
                            <div class="container-fluid">
                                <!-- Brand and toggle get grouped for better mobile display -->
                                <div class="navbar-header">
                                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                                        <span class="sr-only">Toggle navigation</span>
                                        <span class="icon-bar"></span>
                                        <span class="icon-bar"></span>
                                        <span class="icon-bar"></span>
                                    </button>
                                    @*<a class="navbar-brand" href="#">
                                            <img src="~/Image/logo.png" alt="Logo">
                                        </a>*@

                                </div>

                                <!-- Collect the nav links, forms, and other content for toggling -->
                                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                                    <div class="pull-right">
                                        <span><button class="btn btn-outline-light"><a href="/Dashboard/Dashboard">Home</a></button></span>&nbsp&nbsp&nbsp
                                        <span><button class="btn btn-outline-light"><a href="">About us</a></button></span>&nbsp&nbsp&nbsp
                                        <span><button class="btn btn-outline-light"><a href="">Blog</a></button></span>&nbsp&nbsp&nbsp
                                        <span><button class="btn btn-outline-light"><a href="">Contacts</a></button></span>&nbsp&nbsp&nbsp
                                        <span><button class="btn btn-outline-light"><a href="/MissingPerson/ManageMissingPerson">Manage Missing Person</a></button></span>
                                    </div>
                                </div><!-- /.navbar-collapse -->
                            </div><!-- /.container-fluid -->
                        </nav>
                    </div>
                </div><!-- .col-md-12 close -->
            </div><!-- .row close -->
        </div><!-- .container close -->
    </nav><!-- header close -->
    <!--Header end-->
    <div>
        <button type="button" class="btn btn-info m-2" style="float: right;" id="addmissingPersonId">Back to List</button>
        @*@Html.ActionLink("Back to List", "ManageMissingPerson")*@
    </div>
    <div class="col-md-10" style="padding-left: 330px">
        <div class="bg-light rounded h-100 p-4">
            @using (Html.BeginForm("AddMissingPerson", "MissingPerson", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                {
                    @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h4>Add Missing Person</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <div class="form-group">
                    @*<label class="control-label col-md-2">First Name</label>*@
                    <div class="col-md-4" style="padding-left: 71px;">@Html.LabelFor(model => model.FirstName, "First Name")</div>
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-4" style="padding-left: 71px;">
                        @Html.LabelFor(model => model.LastName, "Family Name")
                    </div>
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-4" style="padding-left: 71px;">
                        @Html.LabelFor(model => model.DateOfBirth, "Date Of Birth")
                    </div>
                    <div class="col-md-8">
                        <input type="date" name="DateOfBirth" class="form-control" placeholder="dd-MM-yyyy" />
                        @Html.ValidationMessageFor(model => model.DateOfBirth, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-4" style="padding-left: 71px;">
                        @Html.LabelFor(model => model.Address, "Address")
                    </div>
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-4" style="padding-left: 71px;">
                        @Html.LabelFor(model => model.FatherName, "Father Name")
                    </div>
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.FatherName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.FatherName, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-4" style="padding-left: 71px;">
                        @Html.LabelFor(model => model.MotherName, "Mother Name")
                    </div>
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.MotherName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.MotherName, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-4" style="padding-left: 71px;">
                        @Html.LabelFor(model => model.SpouseName, "Spouse Name")
                    </div>
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.SpouseName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.SpouseName, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <img id="imageid" width="200" class="center" />
                </div>
                <div class="form-group">
                    <div class="col-md-4" style="padding-left: 71px;">
                        <label asp-for="File" class="control-label"></label>
                    </div>
                    <div class="col-md-8">
                        <div class="custom-file">
                            <input asp-for="File" class="custom-file-input" id="customFile">
                            <label class="custom-file-label" for="customFile">Choose file</label>
                        </div>
                        <span asp-validation-for="File" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group">
                    <img src="" id="imageid" width="200" class="center" />
                </div>
                <div class="form-group">
                    <div class="col-md-4" style="padding-left: 71px;">
                        @Html.LabelFor(model => model.MissingDate, "Missing Date")
                    </div>
                    <div class="col-md-8">
                        <input type="date" name="MissingDate" class="form-control" placeholder="dd-MM-yyyy" id="customFile" onchange="loadImageFile(event)" />
                        @Html.ValidationMessageFor(model => model.MissingDate, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-5" style="padding-left: 71px;">
                        <label>Publish on Facebook</label>
                    </div>
                    <div class="col-md-7">
                        <label class="switch">
                            <input type="checkbox" id="facebookCheckbox" data-val="true" value="true" name="PublishonFacebook">
                            <span class="slider round"></span>
                        </label>
                    </div>
                    <input name="PublishonFacebook" type="hidden" value="false" />
                </div>
                <div class="form-group">
                    <div class="col-md-5" style="padding-left: 71px;">
                        <label>Publish on Twitter</label>
                    </div>
                    <div class="col-md-7">
                        <label class="switch">
                            <input type="checkbox" id="twitterCheckbox" name="PublishonTwitter" data-val="true" value="true">
                            <span class="slider round"></span>
                        </label>
                    </div>
                    <input name="PublishonTwitter" type="hidden" value="false" />
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10" style="padding-left: 169px;">
                        <input type="submit" value="Create" class="btn btn-info" style="" />
                    </div>
                </div>
            </div>
                }
                }
            </div>
    </div>
</div>
    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>
    <script src="~/js/bootstrap.js"></script>

    <script>

        $(document).ready(function () {

            $("#addmissingPersonId").click(function () {
                window.location.href = window.location.origin + "/MissingPerson/ManageMissingPerson";
            });


            $('#customFile').on('change', function () {
                //get the file name
                var fileName = $(this).val();
                //replace the "Choose a file" label
                $(this).next('.custom-file-label').html(fileName);
                var image = document.getElementById('imageid');
                image.src = URL.createObjectURL(event.target.files[0]);
            });

          
        });
        
    </script>

MissingPersonWebApp/MissingPersonWebApp/Views/MissingPerson/ManageMissingPerson.cshtml
@{
    ViewBag.Title = "addMissingPersonModal";
}
@Html.AntiForgeryToken()
<!--Header-->

<style>
    .modal-backdrop-m {
        z-index: -1;
    }

    .dropdown {
        overflow: hidden;
        color: blue;
    }

        .dropdown .dropbtn {
            font-size: 16px;
            border: none;
            outline: none;
            color: blue;
            padding: 14px 16px;
            background-color: inherit;
            font-family: inherit;
            margin: 0;
        }



    .dropdown-content {
        display: none;
        background-color: #f9f9f9;
        min-width: 50px;
        margin-left: -100px;
    }

        .dropdown-content a {
            color: black;
            padding: 12px 16px;
            text-decoration: none;
            display: block;
            text-align: right;
        }

            .dropdown-content a:hover {
                background-color: #ddd;
            }

    .dropdown:hover .dropdown-content {
        display: block;
    }
</style>

<link href="~/css/CSS/animate.min.css" rel="stylesheet" />
<link href="~/css/CSS/bootstrap.min.css" rel="stylesheet" />
<link href="~/css/CSS/font-awesome.min.css" rel="stylesheet" />
<link href="~/css/CSS/main.css" rel="stylesheet" />
<link href="~/css/CSS/owl.carousel.css" rel="stylesheet" />
<link href="~/css/CSS/responsive.css" rel="stylesheet" />
<link href="https://cdn.datatables.net/1.11.5/css/jquery.dataTables.min.css" rel="stylesheet" />

<section id="hero-area">
    <img class="img-responsive" src="~/Image/header1.png" alt="">
</section>
<div class="container body-content">
    <nav id="navigation">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="block">
                        <nav class="navbar navbar-default">
                            <div class="container-fluid">
                                <!-- Brand and toggle get grouped for better mobile display -->
                                <div class="navbar-header">
                                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                                        <span class="sr-only">Toggle navigation</span>
                                        <span class="icon-bar"></span>
                                        <span class="icon-bar"></span>
                                        <span class="icon-bar"></span>
                                    </button>
                                    @*<a class="navbar-brand" href="#">
                                            <img src="~/Image/logo.png" alt="Logo">
                                        </a>*@

                                </div>

                                <!-- Collect the nav links, forms, and other content for toggling -->
                                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                                    <div class="pull-right">
                                        <span><button class="btn btn-outline-light"><a href="/Dashboard/Dashboard">Home</a></button></span>&nbsp&nbsp&nbsp
                                        <span><button class="btn btn-outline-light"><a href="">About us</a></button></span>&nbsp&nbsp&nbsp
                                        <span><button class="btn btn-outline-light"><a href="">Contact us</a></button></span>&nbsp&nbsp&nbsp
                                        @{
                                            var role = ViewData["role"];
                                            if (role != null && role.ToString() == "admin")
                                            {
                                                <span><button class="btn btn-outline-light"><a href="">Blog</a></button></span>
                                                <span><button class="btn btn-outline-light"><a href = "/MissingPerson/ManageMissingPerson" > Manage Missing Person</a></button></span>
                                                                                <span class="dropdown">
                                                                                    <button class="btn btn-outline-light" style="color: #6590cc;">Manage Account&nbsp<i class="fa fa-caret-down"></i></button>
                                                                                    <span class="dropdown-content">
                                                                                        <a href = "/Facebook/FacebookDashboard" > Manage Facebook Accounts</a>
                                                                                        <a href = "/Twitter/TwitterDashboard" > Manage Twitter Accounts</a>
                                                                                        <a href = "" onclick= "Logout()" > Logout </a >
                                                                                        </span>
                                                                                    </span>
                                                                                }
                                        }
                                    </div>
                                </div><!-- /.navbar-collapse -->
                            </div><!-- /.container-fluid -->
                        </nav>
                    </div>
                </div><!-- .col-md-12 close -->
            </div><!-- .row close -->
        </div><!-- .container close -->
    </nav><!-- header close -->
    <!--Header end-->
    <div class="">
        <div class="bg-light rounded h-100 p-4">
            <div class="title">
                <h3>
                    Missing <span>People</span>
                    <button type="button" class="btn btn-info m-2" style="float: right;" id="addmissingPersonId" onclick="AddMissingPersonPage()">Add</button>
                </h3>

            </div>
            <table class="table table-hover" id="missingpeopletable">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Image</th>
                        <th scope="col">First Name</th>
                        <th scope="col">Last Name</th>
                        <th scope="col">Missing Date</th>
                        <th scope="col">Action</th>
                    </tr>
                </thead>
                <tbody>

            </table>
        </div>
    </div>
</div>


<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>
<script src="~/js/bootstrap.js"></script>

<script>
    $(document).ready(function () {

        //$('#addMissingPersonModal').appendTo("body");

        let url = window.location.origin;
        LoadTable(url);

        $("#addmissingPersonId").click(function (e) {
            window.location.href = origin + "/MissingPerson/AddMissingPerson";
        })


    });

    function EditMissingPerson(id) {
        debugger;
        if (id > 0) {

            window.location.href = window.location.origin + "/MissingPerson/UpdateMissingPerson?id=" + id;

        }

    }

    function DeleteMissingPerson(id) {
        debugger;
        if (id > 0) {
            $.ajax({
                url: window.location.origin + "/MissingPerson/DeleteMissingPerson?id=" + id,
                success: function (result) {
                    debugger;
                    if (result.data == true) {
                        alert("Deleted successfully");

                        var table = $('#missingpeopletable').DataTable();

                        table.destroy();
                        LoadTable(window.location.origin);
                    }
                }
            });
        }
    }

    function LoadTable(url) {

        var table = $('#missingpeopletable').DataTable({
            "bProcessing": true,
            "serverSide": true,
            ordering: true,
            searching: true,
            "ajax": {
                "url": url + "/MissingPerson/GetMissingPeopleDetail",
                "type": "GET"
            },
            "beforeSend": function (xhr) {
                xhr.setRequestHeader("XSRF-TOKEN",
                    $('input:hidden[name="__RequestVerificationToken"]').val());
            },
            "columns": [
                {
                    "data": null,
                    "render": function (data, type, full, meta) {
                        return (meta.row + 1);
                    }
                },
                {
                    "data": null,
                    render: function (data, type, row) {
                        debugger;
                        if (data.imageName == '')
                            return '';
                        else
                            return '<img src="/Image/MissingPeopleImages/' + data.imageName + '" id="" width="100" class="center" />';
                    }
                },
                { "data": "firstName" },
                { "data": "lastName" },
                { "data": "missingDate", "Type": 'date' },
                {
                    "data": null,
                    render: function (data, type, row) {
                        debugger;
                        //if (data.IsFeedbackDone == 1)
                        //    return '<button type="button" class="btn btn-success">Done</button>';
                        //else
                        return '<a class="btn btn-success m-2" onclick ="EditMissingPerson(' + data.id + ')" >Edit</a>' + '  ' +
                            '<a class="btn btn-danger m-2" onclick ="DeleteMissingPerson(' + data.id + ')" >Delete</a>';
                    }
                }
            ],
            "columnDefs": [
                {
                    "render": function (data, type, row) {
                        let dateArry = data.split('T')[0].split('-');
                        return date = dateArry[2] + '-' + dateArry[1] + '-' + dateArry[0]
                    },
                    "targets": 4
                }
            ]
        });


        //setInterval(function () {
        //    table.ajax.reload();
        //}, 30000);

    }
</script>